export { default as About } from './About'
export { default as Directory } from './Directory'
export { default as SEO } from './SEO'
export { default as TitleBar } from './TitleBar'
export { default as Window } from './Window'
export { default as Work } from './Work'
