module.exports = {
  pathPrefix: '/',
  title: 'Lance Guyatt, Web Developer',
  titleAlt: 'Lance Guyatt',
  description: 'Lance Guyatt, Web Developer',
  language: 'en',
  image: `${process.env.GATSBY_SITE_URL}/images/share.png`,
  ogLanguage: 'en_GB',
  favicon: 'src/images/logo.svg',
  shortName: 'Lance Guyatt',
  author: 'Lance Guyatt',
  themeColor: '#6080b0',
  backgroundColor: '#a0a0a0',
  twitter: '@lanceguyatt',
  facebook: 'Lance Guyatt, Web Developer',
  copyrightYear: new Date().getFullYear(),
}
